-- ============================================================
-- BISNISKU.INFO — Migration 006: Sprint 5 — CRM + Customer Database
-- Tables: customers, customer_tags, customer_tag_assignments,
--         customer_segments, customer_segment_members,
--         customer_notes, customer_interactions
-- Source of Truth: Tech Doc v1 + bisnisku-features.md
-- ============================================================

-- ========================
-- ENUMS for Sprint 5
-- ========================
CREATE TYPE customer_stage AS ENUM (
  'lead', 'prospect', 'customer', 'vip', 'churned'
);

CREATE TYPE interaction_type AS ENUM (
  'visit', 'purchase', 'booking', 'inquiry',
  'wa_message', 'review', 'referral', 'complaint',
  'loyalty_redeem', 'promo_used'
);

CREATE TYPE auto_tag_rule AS ENUM (
  'vip',           -- >10 visits
  'new',           -- first 30 days
  'at_risk',       -- >60 days no visit
  'big_spender',   -- >Rp5M total spend
  'loyal',         -- >6 months active
  'birthday_soon', -- birthday within 7 days
  'inactive'       -- >90 days no visit
);

-- ========================
-- CUSTOMERS
-- Central customer record, one per phone/email per business
-- ========================
CREATE TABLE customers (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  business_id   UUID NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  name          TEXT NOT NULL,
  phone         TEXT,
  email         TEXT,
  avatar_url    TEXT,
  stage         customer_stage DEFAULT 'lead',
  source        TEXT DEFAULT 'manual',           -- manual, wa, booking, import, walk_in
  notes_summary TEXT,                            -- AI-generated summary of recent notes

  -- Computed/cached metrics (updated by triggers or cron)
  total_visits    INTEGER DEFAULT 0,
  total_spent     NUMERIC(14,2) DEFAULT 0,
  last_visit_at   TIMESTAMPTZ,
  first_visit_at  TIMESTAMPTZ,
  average_spend   NUMERIC(12,2) DEFAULT 0,
  lifetime_points INTEGER DEFAULT 0,

  -- Personal info
  birthday      DATE,
  address       TEXT,
  gender        TEXT,                            -- 'M', 'F', or NULL

  -- Meta
  is_active     BOOLEAN DEFAULT TRUE,
  created_at    TIMESTAMPTZ DEFAULT now(),
  updated_at    TIMESTAMPTZ DEFAULT now(),

  -- One customer per phone per business (if phone provided)
  UNIQUE NULLS NOT DISTINCT (business_id, phone),
  -- One customer per email per business (if email provided)
  UNIQUE NULLS NOT DISTINCT (business_id, email)
);

CREATE INDEX idx_customers_business ON customers(business_id);
CREATE INDEX idx_customers_stage ON customers(business_id, stage);
CREATE INDEX idx_customers_phone ON customers(business_id, phone) WHERE phone IS NOT NULL;
CREATE INDEX idx_customers_name_search ON customers USING gin(name gin_trgm_ops);
CREATE INDEX idx_customers_last_visit ON customers(business_id, last_visit_at DESC NULLS LAST);
CREATE INDEX idx_customers_total_spent ON customers(business_id, total_spent DESC);

CREATE TRIGGER customers_updated_at
  BEFORE UPDATE ON customers
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ========================
-- CUSTOMER TAGS
-- Merchant-defined tags (e.g., "Regular", "Vegetarian", "Corporate")
-- ========================
CREATE TABLE customer_tags (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  business_id   UUID NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  name          TEXT NOT NULL,
  color         TEXT DEFAULT '#64748B',          -- Hex color for UI
  is_auto       BOOLEAN DEFAULT FALSE,          -- Auto-generated by system
  auto_rule     auto_tag_rule,                  -- Which auto-tag rule created this
  created_at    TIMESTAMPTZ DEFAULT now(),
  UNIQUE(business_id, name)
);

CREATE INDEX idx_customer_tags_business ON customer_tags(business_id);

-- ========================
-- CUSTOMER TAG ASSIGNMENTS (many-to-many)
-- ========================
CREATE TABLE customer_tag_assignments (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id   UUID NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  tag_id        UUID NOT NULL REFERENCES customer_tags(id) ON DELETE CASCADE,
  assigned_by   TEXT DEFAULT 'manual',           -- 'manual', 'auto', 'import'
  created_at    TIMESTAMPTZ DEFAULT now(),
  UNIQUE(customer_id, tag_id)
);

CREATE INDEX idx_cta_customer ON customer_tag_assignments(customer_id);
CREATE INDEX idx_cta_tag ON customer_tag_assignments(tag_id);

-- ========================
-- CUSTOMER SEGMENTS
-- Saved filters / smart lists
-- ========================
CREATE TABLE customer_segments (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  business_id   UUID NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  name          TEXT NOT NULL,
  description   TEXT,
  filters       JSONB NOT NULL DEFAULT '{}',    -- { tags: [], stage: [], minVisits: N, minSpend: N, ... }
  is_dynamic    BOOLEAN DEFAULT TRUE,           -- Auto-refresh membership
  member_count  INTEGER DEFAULT 0,              -- Cached count
  created_at    TIMESTAMPTZ DEFAULT now(),
  updated_at    TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_customer_segments_business ON customer_segments(business_id);

CREATE TRIGGER customer_segments_updated_at
  BEFORE UPDATE ON customer_segments
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ========================
-- CUSTOMER SEGMENT MEMBERS (for static segments)
-- ========================
CREATE TABLE customer_segment_members (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  segment_id    UUID NOT NULL REFERENCES customer_segments(id) ON DELETE CASCADE,
  customer_id   UUID NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  added_at      TIMESTAMPTZ DEFAULT now(),
  UNIQUE(segment_id, customer_id)
);

CREATE INDEX idx_csm_segment ON customer_segment_members(segment_id);
CREATE INDEX idx_csm_customer ON customer_segment_members(customer_id);

-- ========================
-- CUSTOMER NOTES
-- Free-form notes from staff
-- ========================
CREATE TABLE customer_notes (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id   UUID NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  author_id     UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  content       TEXT NOT NULL,
  is_pinned     BOOLEAN DEFAULT FALSE,
  created_at    TIMESTAMPTZ DEFAULT now(),
  updated_at    TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_customer_notes_customer ON customer_notes(customer_id);
CREATE INDEX idx_customer_notes_pinned ON customer_notes(customer_id, is_pinned) WHERE is_pinned = TRUE;

CREATE TRIGGER customer_notes_updated_at
  BEFORE UPDATE ON customer_notes
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ========================
-- CUSTOMER INTERACTIONS
-- Activity log (visits, purchases, bookings, messages, etc.)
-- ========================
CREATE TABLE customer_interactions (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id   UUID NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  business_id   UUID NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  type          interaction_type NOT NULL,
  description   TEXT,
  amount        NUMERIC(12,2),                  -- For purchase/spend interactions
  metadata      JSONB DEFAULT '{}',             -- Extra data per type (booking_id, order_id, etc.)
  recorded_by   UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  occurred_at   TIMESTAMPTZ DEFAULT now(),
  created_at    TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_interactions_customer ON customer_interactions(customer_id);
CREATE INDEX idx_interactions_business ON customer_interactions(business_id);
CREATE INDEX idx_interactions_type ON customer_interactions(business_id, type);
CREATE INDEX idx_interactions_occurred ON customer_interactions(customer_id, occurred_at DESC);

-- ============================================================
-- FUNCTION: Auto-update customer metrics after interaction
-- ============================================================
CREATE OR REPLACE FUNCTION update_customer_metrics()
RETURNS TRIGGER AS $$
BEGIN
  -- Update visit count and last visit
  IF NEW.type = 'visit' THEN
    UPDATE customers SET
      total_visits = total_visits + 1,
      last_visit_at = GREATEST(last_visit_at, NEW.occurred_at),
      first_visit_at = LEAST(COALESCE(first_visit_at, NEW.occurred_at), NEW.occurred_at)
    WHERE id = NEW.customer_id;
  END IF;

  -- Update spending
  IF NEW.amount IS NOT NULL AND NEW.amount > 0 THEN
    UPDATE customers SET
      total_spent = total_spent + NEW.amount,
      average_spend = (total_spent + NEW.amount) / NULLIF(total_visits, 0)
    WHERE id = NEW.customer_id;
  END IF;

  -- Auto-stage upgrade
  UPDATE customers SET
    stage = CASE
      WHEN total_visits > 10 OR total_spent > 5000000 THEN 'vip'
      WHEN total_visits >= 1 THEN 'customer'
      ELSE stage
    END
  WHERE id = NEW.customer_id
    AND stage NOT IN ('vip', 'churned');

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER trg_update_customer_metrics
  AFTER INSERT ON customer_interactions
  FOR EACH ROW EXECUTE FUNCTION update_customer_metrics();

-- ============================================================
-- RLS POLICIES — Sprint 5 Tables
-- Pattern: owner can CRUD their own business's customers
-- ============================================================

ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_tag_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_segments ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_segment_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_interactions ENABLE ROW LEVEL SECURITY;

-- ── Customers ──
CREATE POLICY "customers_owner_all" ON customers
  FOR ALL USING (
    business_id IN (SELECT id FROM businesses WHERE owner_id = auth.uid())
  );

-- ── Customer Tags ──
CREATE POLICY "customer_tags_owner_all" ON customer_tags
  FOR ALL USING (
    business_id IN (SELECT id FROM businesses WHERE owner_id = auth.uid())
  );

-- ── Tag Assignments ──
CREATE POLICY "cta_owner_all" ON customer_tag_assignments
  FOR ALL USING (
    customer_id IN (
      SELECT c.id FROM customers c
      JOIN businesses b ON c.business_id = b.id
      WHERE b.owner_id = auth.uid()
    )
  );

-- ── Segments ──
CREATE POLICY "segments_owner_all" ON customer_segments
  FOR ALL USING (
    business_id IN (SELECT id FROM businesses WHERE owner_id = auth.uid())
  );

-- ── Segment Members ──
CREATE POLICY "segment_members_owner_all" ON customer_segment_members
  FOR ALL USING (
    segment_id IN (
      SELECT s.id FROM customer_segments s
      JOIN businesses b ON s.business_id = b.id
      WHERE b.owner_id = auth.uid()
    )
  );

-- ── Customer Notes ──
CREATE POLICY "customer_notes_owner_all" ON customer_notes
  FOR ALL USING (
    customer_id IN (
      SELECT c.id FROM customers c
      JOIN businesses b ON c.business_id = b.id
      WHERE b.owner_id = auth.uid()
    )
  );

-- ── Customer Interactions ──
CREATE POLICY "interactions_owner_all" ON customer_interactions
  FOR ALL USING (
    business_id IN (SELECT id FROM businesses WHERE owner_id = auth.uid())
  );
